/********************************************************************
* LinkDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LinkDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLinkDict();
extern void G__cpp_setup_inheritanceLinkDict();
extern void G__cpp_setup_typetableLinkDict();
extern void G__cpp_setup_memvarLinkDict();
extern void G__cpp_setup_globalLinkDict();
extern void G__cpp_setup_memfuncLinkDict();
extern void G__cpp_setup_funcLinkDict();
extern void G__set_cpp_environmentLinkDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "GTMerge.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LinkDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LinkDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LinkDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__LinkDictLN_wuDGSEVENT;
extern G__linked_taginfo G__LinkDictLN_wuDFMAEVENT;
extern G__linked_taginfo G__LinkDictLN_DGSEVENT;
extern G__linked_taginfo G__LinkDictLN_DFMAEVENT;
extern G__linked_taginfo G__LinkDictLN_vectorlEwuDGSEVENTcOallocatorlEwuDGSEVENTgRsPgR;
extern G__linked_taginfo G__LinkDictLN_vectorlEwuDGSEVENTcOallocatorlEwuDGSEVENTgRsPgRcLcLiterator;
extern G__linked_taginfo G__LinkDictLN_reverse_iteratorlEvectorlEwuDGSEVENTcOallocatorlEwuDGSEVENTgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDictLN_vectorlEwuDFMAEVENTcOallocatorlEwuDFMAEVENTgRsPgR;
extern G__linked_taginfo G__LinkDictLN_vectorlEwuDFMAEVENTcOallocatorlEwuDFMAEVENTgRsPgRcLcLiterator;
extern G__linked_taginfo G__LinkDictLN_reverse_iteratorlEvectorlEwuDFMAEVENTcOallocatorlEwuDFMAEVENTgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDictLN_vectorlEDGSEVENTcOallocatorlEDGSEVENTgRsPgR;
extern G__linked_taginfo G__LinkDictLN_vectorlEDGSEVENTcOallocatorlEDGSEVENTgRsPgRcLcLiterator;
extern G__linked_taginfo G__LinkDictLN_reverse_iteratorlEvectorlEDGSEVENTcOallocatorlEDGSEVENTgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDictLN_vectorlEDFMAEVENTcOallocatorlEDFMAEVENTgRsPgR;
extern G__linked_taginfo G__LinkDictLN_vectorlEDFMAEVENTcOallocatorlEDFMAEVENTgRsPgRcLcLiterator;
extern G__linked_taginfo G__LinkDictLN_reverse_iteratorlEvectorlEDFMAEVENTcOallocatorlEDFMAEVENTgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<wuDGSEVENT,allocator<wuDGSEVENT> > G__vectorlEwuDGSEVENTcOallocatorlEwuDGSEVENTgRsPgR;
typedef vector<wuDFMAEVENT,allocator<wuDFMAEVENT> > G__vectorlEwuDFMAEVENTcOallocatorlEwuDFMAEVENTgRsPgR;
typedef vector<DGSEVENT,allocator<DGSEVENT> > G__vectorlEDGSEVENTcOallocatorlEDGSEVENTgRsPgR;
typedef vector<DFMAEVENT,allocator<DFMAEVENT> > G__vectorlEDFMAEVENTcOallocatorlEDFMAEVENTgRsPgR;
